// ─── Clinical Healthcare Search Configuration ────────────────────────────────

export const PDL_BASE = "https://api.peopledatalabs.com/v5";

// Healthcare keyword expansions — maps shorthand/specialty to full PDL-searchable terms
export const CLINICAL_KEYWORD_EXPANSIONS: Record<string, string[]> = {
  // Nursing
  "rn": ["registered nurse", "RN"],
  "lpn": ["licensed practical nurse", "LPN"],
  "lvn": ["licensed vocational nurse", "LVN"],
  "np": ["nurse practitioner", "NP", "APRN"],
  "crna": ["certified registered nurse anesthetist", "CRNA", "nurse anesthetist"],
  "cns": ["clinical nurse specialist", "CNS"],
  "icu nurse": ["ICU nurse", "intensive care unit nurse", "critical care nurse"],
  "er nurse": ["emergency room nurse", "ER nurse", "emergency nurse"],
  "or nurse": ["operating room nurse", "OR nurse", "perioperative nurse", "surgical nurse"],
  "nicu nurse": ["NICU nurse", "neonatal intensive care nurse", "neonatal nurse"],
  "l&d nurse": ["labor and delivery nurse", "L&D nurse", "obstetric nurse"],
  "pacu nurse": ["PACU nurse", "post-anesthesia care nurse", "recovery room nurse"],
  "med-surg nurse": ["med-surg nurse", "medical-surgical nurse", "medical surgical nurse"],
  "travel nurse": ["travel nurse", "traveling nurse", "agency nurse"],
  "charge nurse": ["charge nurse", "nurse manager", "unit charge nurse"],
  "nurse educator": ["nurse educator", "nursing instructor", "clinical educator"],
  "home health nurse": ["home health nurse", "home care nurse", "visiting nurse"],
  "hospice nurse": ["hospice nurse", "palliative care nurse"],
  "school nurse": ["school nurse"],
  "psych nurse": ["psychiatric nurse", "psych nurse", "mental health nurse"],
  "wound care nurse": ["wound care nurse", "wound ostomy continence nurse", "WOCN"],

  // Physicians / Doctors
  "doctor": ["physician", "doctor", "MD", "DO"],
  "md": ["physician", "MD", "medical doctor"],
  "do": ["physician", "DO", "doctor of osteopathy", "osteopathic physician"],
  "surgeon": ["surgeon", "surgical"],
  "hospitalist": ["hospitalist", "hospital medicine physician"],
  "intensivist": ["intensivist", "critical care physician"],
  "attending": ["attending physician"],
  "resident": ["resident physician", "medical resident"],
  "fellow": ["fellow", "clinical fellow"],
  "er doctor": ["emergency medicine physician", "emergency physician", "ER physician"],
  "primary care": ["primary care physician", "family medicine", "internal medicine", "general practitioner"],
  "family medicine": ["family medicine physician", "family practice", "family doctor"],
  "internal medicine": ["internal medicine physician", "internist"],
  "pediatrician": ["pediatrician", "pediatric physician"],

  // Allied Health
  "pa": ["physician assistant", "PA", "PA-C"],
  "pa-c": ["physician assistant", "PA-C", "certified physician assistant"],
  "pt": ["physical therapist", "PT", "physiotherapist"],
  "ot": ["occupational therapist", "OT"],
  "slp": ["speech-language pathologist", "SLP", "speech therapist"],
  "rt": ["respiratory therapist", "RT"],
  "rrt": ["registered respiratory therapist", "RRT"],
  "cna": ["certified nursing assistant", "CNA", "nurse aide"],
  "ma": ["medical assistant", "MA"],
  "emt": ["emergency medical technician", "EMT"],
  "paramedic": ["paramedic", "advanced EMT"],
  "rad tech": ["radiologic technologist", "radiology technician", "X-ray technologist"],
  "mri tech": ["MRI technologist", "MRI technician"],
  "ct tech": ["CT technologist", "CT technician"],
  "ultrasound tech": ["ultrasound technologist", "sonographer", "diagnostic medical sonographer"],
  "surgical tech": ["surgical technologist", "surgical technician", "scrub tech"],
  "phlebotomist": ["phlebotomist", "phlebotomy technician"],
  "lab tech": ["laboratory technician", "medical laboratory technician", "MLT"],
  "pharmacist": ["pharmacist", "PharmD", "clinical pharmacist"],
  "pharmacy tech": ["pharmacy technician"],
  "dietitian": ["dietitian", "registered dietitian", "RD", "RDN", "clinical dietitian"],
  "social worker": ["social worker", "MSW", "LCSW", "licensed clinical social worker", "medical social worker"],
  "psychologist": ["psychologist", "clinical psychologist"],
  "counselor": ["counselor", "mental health counselor", "licensed professional counselor", "LPC"],

  // Specialties
  "cardiology": ["cardiologist", "cardiology", "cardiac", "cardiovascular"],
  "orthopedics": ["orthopedic surgeon", "orthopedics", "orthopedic", "orthopaedic"],
  "oncology": ["oncologist", "oncology", "cancer", "hematology-oncology"],
  "neurology": ["neurologist", "neurology", "neuro"],
  "neurosurgery": ["neurosurgeon", "neurosurgery"],
  "gastroenterology": ["gastroenterologist", "gastroenterology", "GI"],
  "pulmonology": ["pulmonologist", "pulmonology", "pulmonary"],
  "nephrology": ["nephrologist", "nephrology", "renal"],
  "endocrinology": ["endocrinologist", "endocrinology"],
  "rheumatology": ["rheumatologist", "rheumatology"],
  "dermatology": ["dermatologist", "dermatology"],
  "urology": ["urologist", "urology"],
  "psychiatry": ["psychiatrist", "psychiatry"],
  "anesthesiology": ["anesthesiologist", "anesthesiology", "anesthesia"],
  "radiology": ["radiologist", "radiology", "diagnostic radiology"],
  "pathology": ["pathologist", "pathology"],
  "obstetrics": ["obstetrician", "OB/GYN", "obstetrics", "gynecology"],
  "ophthalmology": ["ophthalmologist", "ophthalmology", "eye"],
  "ent": ["otolaryngologist", "ENT", "ear nose throat"],
  "plastic surgery": ["plastic surgeon", "plastic surgery", "reconstructive surgery"],
  "vascular surgery": ["vascular surgeon", "vascular surgery"],
  "thoracic surgery": ["thoracic surgeon", "cardiothoracic", "thoracic surgery"],
  "emergency medicine": ["emergency medicine physician", "emergency physician", "ER doctor"],
  "critical care": ["critical care physician", "intensivist", "critical care"],
  "infectious disease": ["infectious disease physician", "infectious disease specialist"],
  "geriatrics": ["geriatrician", "geriatrics", "geriatric medicine"],
  "neonatology": ["neonatologist", "neonatology"],
  "pain management": ["pain management physician", "pain medicine", "pain specialist"],
  "sports medicine": ["sports medicine physician", "sports medicine"],
  "palliative care": ["palliative care physician", "palliative medicine", "hospice and palliative"],
  "wound care": ["wound care specialist", "wound management"],
  "telehealth": ["telehealth", "telemedicine", "virtual care"],
};

// City → metro area expansions (top 105+ US metro areas)
export const METRO_EXPANSIONS: Record<string, string[]> = {
  "new york": ["new york", "manhattan", "brooklyn", "queens", "bronx", "staten island", "jersey city", "newark", "yonkers"],
  "los angeles": ["los angeles", "long beach", "anaheim", "santa monica", "pasadena", "glendale", "burbank"],
  "chicago": ["chicago", "naperville", "evanston", "schaumburg", "aurora", "joliet"],
  "houston": ["houston", "sugar land", "the woodlands", "katy", "pearland", "pasadena"],
  "dallas": ["dallas", "fort worth", "arlington", "plano", "irving", "frisco", "mckinney"],
  "phoenix": ["phoenix", "scottsdale", "mesa", "tempe", "chandler", "gilbert", "glendale"],
  "philadelphia": ["philadelphia", "camden", "wilmington", "cherry hill"],
  "san antonio": ["san antonio", "new braunfels"],
  "san diego": ["san diego", "chula vista", "carlsbad", "oceanside"],
  "san francisco": ["san francisco", "oakland", "san jose", "berkeley", "fremont", "palo alto", "mountain view"],
  "austin": ["austin", "round rock", "cedar park", "georgetown"],
  "seattle": ["seattle", "tacoma", "bellevue", "kirkland", "redmond", "everett"],
  "denver": ["denver", "aurora", "lakewood", "boulder", "colorado springs"],
  "boston": ["boston", "cambridge", "somerville", "quincy", "brookline", "worcester"],
  "atlanta": ["atlanta", "marietta", "sandy springs", "roswell", "alpharetta", "decatur"],
  "miami": ["miami", "fort lauderdale", "west palm beach", "hialeah", "coral gables", "boca raton"],
  "nashville": ["nashville", "murfreesboro", "franklin"],
  "minneapolis": ["minneapolis", "saint paul", "st paul", "bloomington", "eden prairie"],
  "detroit": ["detroit", "warren", "dearborn", "ann arbor", "sterling heights"],
  "portland": ["portland", "beaverton", "hillsboro", "gresham"],
  "charlotte": ["charlotte", "concord", "gastonia"],
  "tampa": ["tampa", "st petersburg", "clearwater", "brandon"],
  "orlando": ["orlando", "kissimmee", "sanford"],
  "pittsburgh": ["pittsburgh", "cranberry township"],
  "sacramento": ["sacramento", "roseville", "elk grove"],
  "las vegas": ["las vegas", "henderson", "north las vegas"],
  "baltimore": ["baltimore", "towson", "columbia"],
  "milwaukee": ["milwaukee", "waukesha", "west allis"],
  "indianapolis": ["indianapolis", "carmel", "fishers"],
  "columbus": ["columbus", "dublin", "westerville"],
  "kansas city": ["kansas city", "overland park", "olathe"],
  "cleveland": ["cleveland", "akron", "parma"],
  "cincinnati": ["cincinnati", "covington", "newport"],
  "raleigh": ["raleigh", "durham", "chapel hill", "cary"],
  "st louis": ["st louis", "saint louis", "o'fallon", "st charles"],
  "salt lake city": ["salt lake city", "west valley city", "provo", "orem"],
  "richmond": ["richmond", "henrico", "chesterfield"],
  "jacksonville": ["jacksonville", "st augustine"],
  "memphis": ["memphis", "germantown", "bartlett"],
  "louisville": ["louisville", "jeffersontown"],
  "oklahoma city": ["oklahoma city", "norman", "edmond"],
  "new orleans": ["new orleans", "metairie", "kenner"],
  "birmingham": ["birmingham", "hoover", "vestavia hills"],
  "buffalo": ["buffalo", "cheektowaga", "niagara falls"],
  "rochester": ["rochester", "greece", "irondequoit"],
  "hartford": ["hartford", "west hartford", "new haven"],
  "providence": ["providence", "warwick", "cranston"],
};

// US state name mapping for location parsing
export const US_STATES: Record<string, string> = {
  "alabama": "alabama", "alaska": "alaska", "arizona": "arizona", "arkansas": "arkansas",
  "california": "california", "colorado": "colorado", "connecticut": "connecticut",
  "delaware": "delaware", "florida": "florida", "georgia": "georgia", "hawaii": "hawaii",
  "idaho": "idaho", "illinois": "illinois", "indiana": "indiana", "iowa": "iowa",
  "kansas": "kansas", "kentucky": "kentucky", "louisiana": "louisiana", "maine": "maine",
  "maryland": "maryland", "massachusetts": "massachusetts", "michigan": "michigan",
  "minnesota": "minnesota", "mississippi": "mississippi", "missouri": "missouri",
  "montana": "montana", "nebraska": "nebraska", "nevada": "nevada",
  "new hampshire": "new hampshire", "new jersey": "new jersey", "new mexico": "new mexico",
  "new york": "new york", "north carolina": "north carolina", "north dakota": "north dakota",
  "ohio": "ohio", "oklahoma": "oklahoma", "oregon": "oregon", "pennsylvania": "pennsylvania",
  "rhode island": "rhode island", "south carolina": "south carolina", "south dakota": "south dakota",
  "tennessee": "tennessee", "texas": "texas", "utah": "utah", "vermont": "vermont",
  "virginia": "virginia", "washington": "washington", "west virginia": "west virginia",
  "wisconsin": "wisconsin", "wyoming": "wyoming",
};

// Credential prefixes to strip from names
export const CREDENTIAL_PREFIX_REGEX = /^(faaos|caqsm|facp|facs|facep|faap|facog|md|do|rn|bsn|msn|dnp|phd|mph|dpm|dds|dmd|aprn|np|pa-c|pt|ot|slp|rd|ldn|pharmd)\s+/i;

// Healthcare industry allowlist for PDL queries
export const HEALTHCARE_INDUSTRIES = [
  "hospitals and health care",
  "medical practices",
  "hospitals",
  "health care",
  "mental health care",
  "individual and family services",
  "nursing",
  "pharmaceutical manufacturing",
  "biotechnology research",
  "medical equipment manufacturing",
  "ambulance services",
  "outpatient care centers",
  "home health care services",
  "rehabilitation",
  "chiropractors",
  "optometrists",
  "dentists",
  "physical therapy",
  "veterinary services",
];

// Non-clinical roles to exclude from results
export const EXCLUDED_TITLE_PATTERNS = [
  "sales representative",
  "medical device sales",
  "pharmaceutical sales",
  "account executive",
  "business development",
  "medical device rep",
  "pharma rep",
  "territory manager",
  "regional sales",
  "commercial",
];

// Rate limits
export const RATE_LIMIT_SEARCHES_PER_HOUR = 100;
export const CACHE_TTL_HOURS = 4;
export const MAX_QUERY_LENGTH = 500;
export const PDL_BATCH_SIZE = 100;
export const UI_PAGE_SIZE = 15;
